// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw5vDxEaIkB-8rYdiM9eKqk3XgSC1SrxM',
    appId: '1:355890748835:web:fab3a0539c9cc013530e16',
    messagingSenderId: '355890748835',
    projectId: 'been-ther',
    authDomain: 'been-ther.firebaseapp.com',
    storageBucket: 'been-ther.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMMSaxycevbzB3vEDdHVQhafuia0u6uRs',
    appId: '1:355890748835:android:e594d664368b118f530e16',
    messagingSenderId: '355890748835',
    projectId: 'been-ther',
    storageBucket: 'been-ther.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3VOgeCgdusTOvDiYJcdcqifHw84QWInI',
    appId: '1:355890748835:ios:e61c53920e750021530e16',
    messagingSenderId: '355890748835',
    projectId: 'been-ther',
    storageBucket: 'been-ther.firebasestorage.app',
    iosBundleId: 'com.example.beenThere2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3VOgeCgdusTOvDiYJcdcqifHw84QWInI',
    appId: '1:355890748835:ios:e61c53920e750021530e16',
    messagingSenderId: '355890748835',
    projectId: 'been-ther',
    storageBucket: 'been-ther.firebasestorage.app',
    iosBundleId: 'com.example.beenThere2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw5vDxEaIkB-8rYdiM9eKqk3XgSC1SrxM',
    appId: '1:355890748835:web:de9da6e2acf93661530e16',
    messagingSenderId: '355890748835',
    projectId: 'been-ther',
    authDomain: 'been-ther.firebaseapp.com',
    storageBucket: 'been-ther.firebasestorage.app',
  );
}
